name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run spring test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '16'
         cache: npm
         cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        working-directory: ./web
        run: npm ci
      - name: Build
        working-directory: ./web
        run: npm run build
      - name: Test
        working-directory: ./web
        run: npm run ci
